services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nginx-frontend
    ports:
      - "80:80"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge